Update using statements in Guides
elsa-workflows/elsa-website pull request #12
Opened 2021-02-08 12:56 UTC by terle

Hi 👋, Total n00b in Elsa here. But I'm really exited to begin working with it/her.

So I wanted to learn and began following the guides, I noticed some inconsistencies and bad-red-squiggly lines. Seems like the examples might be outdated.

So I fixed them . Please review 😄 

I might not have gotten everything right; but I expect a more seasoned Elsa-developer will easily spot any mistakes.
Basically, I fixed:
 - Servicecollection extension is _no longer_ named `AddElsa()` but `AddElsaCore()`
 - Added additinal nuget-references
 - Added additional ServiceCollection Extension calls/configuration as needed (hopefully I did it correct 🤞

Thanks

2021-02-08 12:56 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/elsa-workflows/elsa-website?pullRequest=12) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/elsa-workflows/elsa-website?pullRequest=12) before we can accept your contribution.<br/><br/>:x: terle [sign now](https://cla.dotnetfoundation.org/elsa-workflows/elsa-website?pullRequest=12)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/elsa-workflows/elsa-website?pullRequest=12) it.</sub>

2021-03-06 12:46 UTC, sfmskywalker requested changes
Thanks so much for your PR!

If you could please review my comment and push an update then I'd gladly take in your PR.

2021-03-06 12:46 UTC, sfmskywalker commented on docs/guides-document-approval.md
> -                .AddElsa()
Actually, `.AddElsa()` is still supported and the most convenient way to install Elsa into DI. `.AddElsaCore()` also works, but requires the developer to register additional services manually (if they want to use them).

2021-07-11 12:03 UTC, sfmskywalker approved these changes

2021-08-02 10:36 UTC, merged